In [1]:
import pandas as pd
import numpy as np

data = pd.read_csv('./games.csv')

In [2]:
data.head()

,Name,Platform,Year_of_Release,Genre,NA_sales,EU_sales,JP_sales,Other_sales,Critic_Score,User_Score,Rating
0,Wii Sports,Wii,2006.0,Sports,41.36,28.96,3.77,8.45,76.0,8,E
1,Super Mario Bros.,NES,1985.0,Platform,29.08,3.58,6.81,0.77,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,15.68,12.76,3.79,3.29,82.0,8.3,E
3,Wii Sports Resort,Wii,2009.0,Sports,15.61,10.93,3.28,2.95,80.0,8,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,11.27,8.89,10.22,1.00,NaN,NaN,NaN

In [3]:
data

,Name,Platform,Year_of_Release,Genre,NA_sales,EU_sales,JP_sales,Other_sales,Critic_Score,User_Score,Rating
0,Wii Sports,Wii,2006.0,Sports,41.36,28.96,3.77,8.45,76.0,8,E
1,Super Mario Bros.,NES,1985.0,Platform,29.08,3.58,6.81,0.77,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,15.68,12.76,3.79,3.29,82.0,8.3,E
3,Wii Sports Resort,Wii,2009.0,Sports,15.61,10.93,3.28,2.95,80.0,8,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,11.27,8.89,10.22,1.00,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
16710,Samurai Warriors: Sanada Maru,PS3,2016.0,Action,0.00,0.00,0.01,0.00,NaN,NaN,NaN
16711,LMA Manager 2007,X360,2006.0,Sports,0.00,0.01,0.00,0.00,NaN,NaN,NaN
16712,Haitaka no Psychedelica,PSV,2016.0,Adventure,0.00,0.00,0.01,0.00,NaN,NaN,NaN
16713,Spirits & Spells,GBA,2003.0,Platform,0.01,0.00,0.00,0.00,NaN,NaN,NaN
16714,Winning Post 8 2016,PSV,2016.0,Simulation,0.00,0.00,0.01,0.00,NaN,NaN,NaN

In [4]:
pd.unique(data['Platform'])

array(['Wii', 'NES', 'GB', 'DS', 'X360', 'PS3', 'PS2', 'SNES', 'GBA',
       'PS4', '3DS', 'N64', 'PS', 'XB', 'PC', '2600', 'PSP', 'XOne',
       'WiiU', 'GC', 'GEN', 'DC', 'PSV', 'SAT', 'SCD', 'WS', 'NG', 'TG16',
       '3DO', 'GG', 'PCFX'], dtype=object)

In [5]:
data.drop_duplicates()

,Name,Platform,Year_of_Release,Genre,NA_sales,EU_sales,JP_sales,Other_sales,Critic_Score,User_Score,Rating
0,Wii Sports,Wii,2006.0,Sports,41.36,28.96,3.77,8.45,76.0,8,E
1,Super Mario Bros.,NES,1985.0,Platform,29.08,3.58,6.81,0.77,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,15.68,12.76,3.79,3.29,82.0,8.3,E
3,Wii Sports Resort,Wii,2009.0,Sports,15.61,10.93,3.28,2.95,80.0,8,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,11.27,8.89,10.22,1.00,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
16710,Samurai Warriors: Sanada Maru,PS3,2016.0,Action,0.00,0.00,0.01,0.00,NaN,NaN,NaN
16711,LMA Manager 2007,X360,2006.0,Sports,0.00,0.01,0.00,0.00,NaN,NaN,NaN
16712,Haitaka no Psychedelica,PSV,2016.0,Adventure,0.00,0.00,0.01,0.00,NaN,NaN,NaN
16713,Spirits & Spells,GBA,2003.0,Platform,0.01,0.00,0.00,0.00,NaN,NaN,NaN
16714,Winning Post 8 2016,PSV,2016.0,Simulation,0.00,0.00,0.01,0.00,NaN,NaN,NaN

In [6]:
data.describe()

,Year_of_Release,NA_sales,EU_sales,JP_sales,Other_sales,Critic_Score
count,16446.000000,16715.000000,16715.000000,16715.000000,16715.000000,8137.000000
mean,2006.484616,0.263377,0.145060,0.077617,0.047342,68.967679
std,5.877050,0.813604,0.503339,0.308853,0.186731,13.938165
min,1980.000000,0.000000,0.000000,0.000000,0.000000,13.000000
25%,2003.000000,0.000000,0.000000,0.000000,0.000000,60.000000
50%,2007.000000,0.080000,0.020000,0.000000,0.010000,71.000000
75%,2010.000000,0.240000,0.110000,0.040000,0.030000,79.000000
max,2016.000000,41.360000,28.960000,10.220000,10.570000,98.000000

In [7]:
data.loc[data['Platform'] == 'GEN']

,Name,Platform,Year_of_Release,Genre,NA_sales,EU_sales,JP_sales,Other_sales,Critic_Score,User_Score,Rating
145,Sonic the Hedgehog 2,GEN,1992.0,Platform,4.47,1.20,0.16,0.19,NaN,NaN,NaN
257,Sonic the Hedgehog,GEN,1991.0,Platform,3.03,0.91,0.26,0.13,NaN,NaN,NaN
564,Mortal Kombat,GEN,1992.0,Fighting,1.95,0.63,0.00,0.09,NaN,NaN,NaN
588,Streets of Rage,GEN,1990.0,Action,1.86,0.55,0.11,0.08,NaN,NaN,NaN
659,NaN,GEN,1993.0,NaN,1.78,0.53,0.00,0.08,NaN,NaN,NaN
832,NBA Jam,GEN,1992.0,Sports,1.75,0.25,0.00,0.05,NaN,NaN,NaN
960,Sonic & Knuckles,GEN,1994.0,Platform,1.24,0.43,0.03,0.12,NaN,NaN,NaN
996,Sonic the Hedgehog 3,GEN,1994.0,Platform,1.02,0.47,0.20,0.07,NaN,NaN,NaN
1099,Street Fighter II': Special Champion Edition,GEN,1992.0,Fighting,1.00,0.30,0.31,0.04,NaN,NaN,NaN
1365,Disney's The Lion King,GEN,1994.0,Platform,0.97,0.37,0.03,0.05,NaN,NaN,NaN
1453,Mortal Kombat 3,GEN,1994.0,Fighting,1.03,0.27,0.00,0.04,NaN,NaN,NaN
1842,NBA Jam Tournament Edition,GEN,1994.0,Sports,0.95,0.14,0.00,0.03,NaN,NaN,NaN
6451,Virtua Racing,GEN,1994.0,Racing,0.00,0.00,0.26,0.00,NaN,NaN,NaN
7885,Shining Force II,GEN,1993.0,Strategy,0.00,0.00,0.19,0.00,NaN,NaN,NaN
8893,Super Street Fighter II,GEN,1993.0,Fighting,0.00,0.00,0.15,0.00,NaN,NaN,NaN
9000,"Lunar 2: Eternal Blue(sales, but wrong system)",GEN,1994.0,Role-Playing,0.00,0.00,0.14,0.00,NaN,NaN,NaN
9563,Gunstar Heroes,GEN,1992.0,Shooter,0.00,0.00,0.13,0.00,NaN,NaN,NaN
9787,Ecco the Dolphin,GEN,1992.0,Adventure,0.00,0.00,0.12,0.00,NaN,NaN,NaN
11563,Yuu Yuu Hakusho: Makyo Toitsusen,GEN,1994.0,Fighting,0.00,0.00,0.08,0.00,NaN,NaN,NaN
11660,Dragon Slayer: The Legend of Heroes,GEN,1994.0,Role-Playing,0.00,0.00,0.08,0.00,NaN,NaN,NaN
11986,Ecco: The Tides of Time,GEN,1993.0,Adventure,0.00,0.00,0.07,0.00,NaN,NaN,NaN
12098,Street Fighter II': Special Champion Edition (...,GEN,1993.0,Action,0.00,0.00,0.07,0.00,NaN,NaN,NaN
12264,Streets of Rage 3,GEN,1993.0,Action,0.00,0.00,0.07,0.00,NaN,NaN,NaN
12984,Dynamite Headdy,GEN,1993.0,Platform,0.00,0.00,0.05,0.00,NaN,NaN,NaN
13343,Beyond Oasis,GEN,1993.0,Role-Playing,0.00,0.00,0.05,0.00,NaN,NaN,NaN
14085,J-League Pro Striker 2,GEN,1994.0,Sports,0.00,0.00,0.04,0.00,NaN,NaN,NaN
14132,Castlevania Bloodlines,GEN,1994.0,Platform,0.00,0.00,0.04,0.00,NaN,NaN,NaN
14244,NaN,GEN,1993.0,NaN,0.00,0.00,0.03,0.00,NaN,NaN,NaN
14488,Puzzle & Action: Tant-R,GEN,1994.0,Misc,0.00,0.00,0.03,0.00,NaN,NaN,NaN

In [8]:
data['Name'].isna().index

RangeIndex(start=0, stop=16715, step=1)

In [9]:
data.groupby(by="Platform").count()

,Name,Year_of_Release,Genre,NA_sales,EU_sales,JP_sales,Other_sales,Critic_Score,User_Score,Rating
Platform,,,,,,,,,,
2600,133,116,133,133,133,133,133,0,0,0
3DO,3,3,3,3,3,3,3,0,0,0
3DS,520,512,520,520,520,520,520,168,230,228
DC,52,52,52,52,52,52,52,14,14,14
DS,2151,2121,2151,2151,2151,2151,2151,717,1272,1273
GB,98,97,98,98,98,98,98,0,0,0
GBA,822,811,822,822,822,822,822,438,517,522
GC,556,542,556,556,556,556,556,448,469,469
GEN,27,29,27,29,29,29,29,0,0,0
GG,1,1,1,1,1,1,1,0,0,0
N64,319,316,319,319,319,319,319,0,0,0
NES,98,98,98,98,98,98,98,0,0,0
NG,12,12,12,12,12,12,12,0,0,0
PC,974,957,974,974,974,974,974,715,819,774
PCFX,1,1,1,1,1,1,1,0,0,0
PS,1197,1190,1197,1197,1197,1197,1197,200,207,208
PS2,2161,2127,2161,2161,2161,2161,2161,1298,1481,1481
PS3,1331,1306,1331,1331,1331,1331,1331,820,964,952
PS4,392,392,392,392,392,392,392,252,263,255
PSP,1209,1193,1209,1209,1209,1209,1209,462,544,544
PSV,430,429,430,430,430,430,430,120,150,151
SAT,173,173,173,173,173,173,173,0,0,0
SCD,6,6,6,6,6,6,6,0,0,0
SNES,239,239,239,239,239,239,239,0,0,0
TG16,2,2,2,2,2,2,2,0,0,0
WS,6,6,6,6,6,6,6,0,0,0
Wii,1320,1286,1320,1320,1320,1320,1320,585,1000,1002
WiiU,147,147,147,147,147,147,147,90,105,105
X360,1262,1232,1262,1262,1262,1262,1262,916,1050,1052
XB,824,803,824,824,824,824,824,725,736,733
XOne,247,247,247,247,247,247,247,169,193,186

Отсюда убираем всё, что имеет меньше 10 записей (3DO, GG, PCFX, SCD, TG16, WS). Остаток - 16697. Остаток на выброс - 1652

In [10]:
platforms = ["3DO", "GG", "PCFX", "SCD", "TG16", "WS"]
for platform in platforms:
    data = data.drop(data[data['Platform']==platform].index)

In [11]:
data.groupby(by="Platform").count()

,Name,Year_of_Release,Genre,NA_sales,EU_sales,JP_sales,Other_sales,Critic_Score,User_Score,Rating
Platform,,,,,,,,,,
2600,133,116,133,133,133,133,133,0,0,0
3DS,520,512,520,520,520,520,520,168,230,228
DC,52,52,52,52,52,52,52,14,14,14
DS,2151,2121,2151,2151,2151,2151,2151,717,1272,1273
GB,98,97,98,98,98,98,98,0,0,0
GBA,822,811,822,822,822,822,822,438,517,522
GC,556,542,556,556,556,556,556,448,469,469
GEN,27,29,27,29,29,29,29,0,0,0
N64,319,316,319,319,319,319,319,0,0,0
NES,98,98,98,98,98,98,98,0,0,0
NG,12,12,12,12,12,12,12,0,0,0
PC,974,957,974,974,974,974,974,715,819,774
PS,1197,1190,1197,1197,1197,1197,1197,200,207,208
PS2,2161,2127,2161,2161,2161,2161,2161,1298,1481,1481
PS3,1331,1306,1331,1331,1331,1331,1331,820,964,952
PS4,392,392,392,392,392,392,392,252,263,255
PSP,1209,1193,1209,1209,1209,1209,1209,462,544,544
PSV,430,429,430,430,430,430,430,120,150,151
SAT,173,173,173,173,173,173,173,0,0,0
SNES,239,239,239,239,239,239,239,0,0,0
Wii,1320,1286,1320,1320,1320,1320,1320,585,1000,1002
WiiU,147,147,147,147,147,147,147,90,105,105
X360,1262,1232,1262,1262,1262,1262,1262,916,1050,1052
XB,824,803,824,824,824,824,824,725,736,733
XOne,247,247,247,247,247,247,247,169,193,186

In [12]:
data.loc[data['Name'].isna()]

,Name,Platform,Year_of_Release,Genre,NA_sales,EU_sales,JP_sales,Other_sales,Critic_Score,User_Score,Rating
659,NaN,GEN,1993.0,NaN,1.78,0.53,0.00,0.08,NaN,NaN,NaN
14244,NaN,GEN,1993.0,NaN,0.00,0.00,0.03,0.00,NaN,NaN,NaN

Также убираем записи, которые не имеют названия (Name = NaN). Остаток - 16695. Остаток на выброс - 1650

In [13]:
data = data.drop(data[data['Name'].isna()].index)

Далее проверим руками, есть ли на Metacritic оценки для платформ, которые не имеют оценки ни на одну игру

Для следующих платформ оценок нет: Atari 2600 (2600), GameBoy (GB), Sega Mega Drive (GEN), NES, Neo-Geo AES (NG), Sega Saturn (SAT), Super NES (SNES). Их придётся выкинуть: остаток - 15915, остаток на выброс - 870

Из всего списка, оценки возможно найти только для Nintendo 64.

In [14]:
platforms = ["2600", "GB", "GEN", "NES", "NG", "SAT", "SNES"]
for platform in platforms:
    data = data.drop(data[data['Platform']==platform].index)

In [15]:
data.groupby(by="Platform").count()

,Name,Year_of_Release,Genre,NA_sales,EU_sales,JP_sales,Other_sales,Critic_Score,User_Score,Rating
Platform,,,,,,,,,,
3DS,520,512,520,520,520,520,520,168,230,228
DC,52,52,52,52,52,52,52,14,14,14
DS,2151,2121,2151,2151,2151,2151,2151,717,1272,1273
GBA,822,811,822,822,822,822,822,438,517,522
GC,556,542,556,556,556,556,556,448,469,469
N64,319,316,319,319,319,319,319,0,0,0
PC,974,957,974,974,974,974,974,715,819,774
PS,1197,1190,1197,1197,1197,1197,1197,200,207,208
PS2,2161,2127,2161,2161,2161,2161,2161,1298,1481,1481
PS3,1331,1306,1331,1331,1331,1331,1331,820,964,952
PS4,392,392,392,392,392,392,392,252,263,255
PSP,1209,1193,1209,1209,1209,1209,1209,462,544,544
PSV,430,429,430,430,430,430,430,120,150,151
Wii,1320,1286,1320,1320,1320,1320,1320,585,1000,1002
WiiU,147,147,147,147,147,147,147,90,105,105
X360,1262,1232,1262,1262,1262,1262,1262,916,1050,1052
XB,824,803,824,824,824,824,824,725,736,733
XOne,247,247,247,247,247,247,247,169,193,186

Далее создадим датафреймы под каждую оставшуюся платформу и сделаем экспорт в CSV

In [16]:
df_3ds = data.loc[data['Platform'] == "3DS"]
df_dc = data.loc[data['Platform'] == "DC"]
df_ds = data.loc[data['Platform'] == "DS"]
df_gba = data.loc[data['Platform'] == "GBA"]
df_gc = data.loc[data['Platform'] == "GC"]
df_nintendo64 = data.loc[data['Platform'] == "N64"]
df_pc = data.loc[data['Platform'] == "PC"]
df_ps1 = data.loc[data['Platform'] == "PS"]
df_ps2 = data.loc[data['Platform'] == "PS2"]
df_ps3 = data.loc[data['Platform'] == "PS3"]
df_ps4 = data.loc[data['Platform'] == "PS4"]
df_psp = data.loc[data['Platform'] == "PSP"]
df_psvita = data.loc[data['Platform'] == "PSV"]
df_wii = data.loc[data['Platform'] == "Wii"]
df_wiiu = data.loc[data['Platform'] == "WiiU"]
df_xbox360 = data.loc[data['Platform'] == "X360"]
df_xbox = data.loc[data['Platform'] == "XB"]
df_xboxone = data.loc[data['Platform'] == "XOne"]

In [36]:
df_3ds.to_csv(r'.\PycharmProjects\ParserMetacritic\datasets\3DS.csv')
df_dc.to_csv(r'.\PycharmProjects\ParserMetacritic\datasets\Dreamcast.csv')
df_ds.to_csv(r'.\PycharmProjects\ParserMetacritic\datasets\DS.csv')
df_gba.to_csv(r'.\PycharmProjects\ParserMetacritic\datasets\Game Boy Advance.csv')
df_gc.to_csv(r'.\PycharmProjects\ParserMetacritic\datasets\GameCube.csv')
df_nintendo64.to_csv(r'.\PycharmProjects\ParserMetacritic\datasets\Nintendo 64.csv')
df_pc.to_csv(r'.\PycharmProjects\ParserMetacritic\datasets\pc.csv')
df_ps1.to_csv(r'.\PycharmProjects\ParserMetacritic\datasets\PlayStation.csv')
df_ps2.to_csv(r'.\PycharmProjects\ParserMetacritic\datasets\PlayStation 2.csv')
df_ps3.to_csv(r'.\PycharmProjects\ParserMetacritic\datasets\PlayStation3.csv')
df_ps4.to_csv(r'.\PycharmProjects\ParserMetacritic\datasets\PlayStation4.csv')
df_psp.to_csv(r'.\PycharmProjects\ParserMetacritic\datasets\PSP.csv')
df_psvita.to_csv(r'.\PycharmProjects\ParserMetacritic\datasets\PlayStation Vita.csv')
df_wii.to_csv(r'.\PycharmProjects\ParserMetacritic\datasets\Wii.csv')
df_wiiu.to_csv(r'.\PycharmProjects\ParserMetacritic\datasets\Wii U.csv')
df_xbox360.to_csv(r'.\PycharmProjects\ParserMetacritic\datasets\XBOX 360.csv')
df_xbox.to_csv(r'.\PycharmProjects\ParserMetacritic\datasets\Xbox.csv')
df_xboxone.to_csv(r'.\PycharmProjects\ParserMetacritic\datasets\XBOX ONE.csv')

Далее, загрузим полученные датасеты в парсер

In [31]:
print(df_3ds)

                                                    Name Platform  \
33                                   Pokemon X/Pokemon Y      3DS
40                                          Mario Kart 7      3DS
47             Pokemon Omega Ruby/Pokemon Alpha Sapphire      3DS
53                                   Super Mario 3D Land      3DS
62                               New Super Mario Bros. 2      3DS
...                                                  ...      ...
16648                                       Mushi Bugyou      3DS
16653  Nintendogs and Cats Golden Retriever and New F...      3DS
16668  Fujiko F. Fujio Characters: Great Assembly! Sl...      3DS
16677                   Aikatsu Stars! My Special Appeal      3DS
16688                      Outdoors Unleashed: Africa 3D      3DS

       Year_of_Release         Genre  NA_sales  EU_sales  JP_sales  \
33              2013.0  Role-Playing      5.28      4.19      4.35
40              2011.0        Racing      5.03      4.02      2.69
47              2014.0  Role-Playing      4.35      3.49      3.10
53              2011.0      Platform      4.89      3.00      2.14
62              2012.0      Platform      3.66      3.14      2.47
...                ...           ...       ...       ...       ...
16648           2013.0        Action      0.00      0.00      0.01
16653           2011.0        Action      0.00      0.01      0.00
16668           2014.0        Action      0.00      0.00      0.01
16677           2016.0        Action      0.00      0.00      0.01
16688           2011.0        Sports      0.01      0.00      0.00

       Other_sales  Critic_Score User_Score Rating
33            0.78           NaN        NaN    NaN
40            0.91          85.0        8.2      E
47            0.74           NaN        NaN    NaN
53            0.78          90.0        8.4      E
62            0.63          78.0        7.2      E
...            ...           ...        ...    ...
16648         0.00           NaN        NaN    NaN
16653         0.00           NaN        NaN    NaN
16668         0.00           NaN        NaN    NaN
16677         0.00           NaN        NaN    NaN
16688         0.00           NaN        tbd      T

[520 rows x 11 columns]